services:
  backend:
    build: ./backend
    container_name: schedulink-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - frontend

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: schedulink-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true


